# Generated by Django 3.2.12 on 2022-03-18 15:53

import articles.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=articles.utils.get_article_image_upload_to)),
                ('publish_status', models.CharField(choices=[('pub', 'Publish'), ('dra', 'DRAFT'), ('pri', 'Private')], default='dra', max_length=3)),
                ('publish_timestamp', models.DateTimeField(blank=True, help_text='Field-driven publish timestamp', null=True)),
                ('user_publish_timestamp', models.DateTimeField(blank=True, help_text='User-defined publish timestamp', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-user_publish_timestamp', '-publish_timestamp', '-updated'],
            },
        ),
    ]
