version: "3.9"

services:
  mysql_db:
    image: mysql:8.0.26
    restart: always
    env_file: .env
    ports:
      - "3007:3007"
    expose:
      - 3007
    volumes:
      - mysql-volume:/var/lib/mysql
    profiles:
      - mysql
  postgres_db:
    image: postgres
    restart: always
    command: -p 5431
    env_file:
      - .env
    expose:
      - 5431
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    profiles:
      - postgres
  redis_db:
    image: redis
    restart: always
    expose:
      - 6388
    ports:
      - "6388:6388"
    volumes:
        - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6388
    profiles:
      - mysql
      - postgres
      - redis

volumes:
  mysql-volume:
  postgres_data:
  redis_data: 