import os

LINODE_BUCKET = os.environ.get("LINODE_BUCKET")
LINODE_BUCKET_REGION = os.environ.get("LINODE_BUCKET_REGION")
LINODE_BUCKET_ACCESS_KEY = os.environ.get("LINODE_BUCKET_ACCESS_KEY")
LINODE_BUCKET_SECRET_KEY = os.environ.get("LINODE_BUCKET_SECRET_KEY")
LINODE_OBJECT_STORAGE_READY = all([LINODE_BUCKET, LINODE_BUCKET_REGION, LINODE_BUCKET_ACCESS_KEY, LINODE_BUCKET_SECRET_KEY])

if LINODE_OBJECT_STORAGE_READY:
    AWS_S3_ENDPOINT_URL = f"https://{LINODE_BUCKET_REGION}.linodeobjects.com"
    AWS_ACCESS_KEY_ID = LINODE_BUCKET_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY = LINODE_BUCKET_SECRET_KEY
    AWS_S3_REGION_NAME = LINODE_BUCKET_REGION
    AWS_S3_USE_SSL = True
    AWS_STORAGE_BUCKET_NAME = LINODE_BUCKET
    AWS_DEFAULT_ACL="public-read"
    
    DEFAULT_FILE_STORAGE = "cfeblog.storages.backends.MediaS3BotoStorage"
    STATICFILES_STORAGE = "cfeblog.storages.backends.PublicS3Boto3Storage"    
